### ISSUE TITLE
Create complete pdf app

### ISSUE THREAD

**Issue by odmfl** [Varshithvhegde/PDFSign#3]
Could you create a complete pdf app which also implemented the signature function which is present in this app?

There are currently some "pdf app" projects on GitHub but they have several problems and others have not been maintained for a long time.

**Comment by Varshithvhegde** [comment]
Yeah sure i would love do complete pdf app but it would be great if you can elaborate the features needed. Thank you

**Comment by odmfl** [comment]
thanks i sent you an email privately about this, where i try to explain a few things to you

**Comment by Varshithvhegde** [comment]
Ok Thak you for your suggestion when i complete my other work i will complete this.
